Feature/signinpage
gpbPiazza/Front-User-Codify pull request #5
Opened 2021-02-03 05:05 UTC by lhnakan

if possible, check the pullrequest of this branch last

2021-02-03 17:41 UTC, thiagoribb approved these changes

2021-02-03 22:25 UTC, vagnerpavani requested changes

2021-02-03 22:25 UTC, vagnerpavani commented on src/pages/SignUp/index.js
> +    console.log(data);
É legal não deixarmos esse tipo de console.log na nossa entrega final.

2021-02-04 23:23 UTC, vagnerpavani requested changes

2021-02-04 23:23 UTC, vagnerpavani commented on src/components/WarningModal/index.js
> +  }
Essa logica parece estar envolvendo a interface na logica do código. Pode valer a pena mandar nesse objeto um status de sucesso ou não. E renderizar o warning baseado nisso, para deixar o código mais semântico.

2021-02-05 06:27 UTC, vagnerpavani approved these changes

2021-02-05 06:28 UTC, merged