Feature/course page
gpbPiazza/Front-User-Codify pull request #7
Opened 2021-02-04 23:20 UTC by thiagoribb

2021-02-04 23:41 UTC, vagnerpavani requested changes

2021-02-04 23:41 UTC, vagnerpavani commented on src/pages/Course/index.js
> +    // }
Não e legal mandarmos blocos de código comentados para produção. Isso pode deixar nosso código confuso a longo prazo.

2021-02-05 01:20 UTC, gpbPiazza requested changes

2021-02-05 01:20 UTC, gpbPiazza commented on src/pages/Course/index.js
> +    // }
Porque não estamos utilizando a rota? Deu tudo certo com a implementação na api?

2021-02-05 16:27 UTC, merged